---
title: "Chinese Local Debt"
author: "Po-Sheng Lee"
output:
  github_document:
    toc: TRUE
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

# Data Processing
```{r package and data}

library(magrittr)
library(tidyverse) 
library(readr)
library(readxl)
library(lubridate)
library(Zelig)
library(plm)
library(sf)
library(leaflet)
library(viridis)


FinancialVehicleDebt <- read_excel("data/LocalGovernmentFinancialVehicleWIND.xlsx", 
    col_types = c("text", "text", "text", 
        "text", "numeric", "numeric", "numeric", 
        "numeric", "date", "numeric", 
        "numeric", "blank", "text", "text", 
        "text", "text", "blank", "blank", 
        "blank", "blank", "blank", "blank", "blank", "blank", 
        "blank", "blank", "blank", "blank", "blank", "blank", 
        "blank", "blank", "blank", "blank", "blank", "blank", 
        "blank"), skip = 1)

GovernmentDebt <- read_excel("data/LocalGovernmentDebt.xlsx", 
    col_types = c("text", "text", "text", 
        "text", "numeric", "numeric", "numeric", 
        "numeric", "date", "numeric", "numeric", 
        "text", "text", "blank", "blank"), 
    skip = 1)


```

```{r clean data}

FinancialVehicleDebt %<>%
  distinct(fullname, issueamount, issuerupdated, .keep_all = TRUE) %>%
  mutate(term = round(term*365/30, digits = 0)) %>%
  mutate(issue_date = maturitydate - months(term)) %>%
  mutate(issue_year = year(issue_date))

GovernmentDebt %<>%
  distinct(fullname, issueamount, issuerupdated, .keep_all = TRUE) %>%
  mutate(issue_date = maturitydate - years(term)) %>%
  mutate(issue_year = year(issue_date))




```


```{r transform data}

LGFV_industry <- FinancialVehicleDebt %>%
  filter(!is.na(abs_province) & !is.na(issue_year) & !is.na(abs_industry) == TRUE) %>%
  group_by(abs_province, issue_year, abs_industry) %>%
  summarise(FVdebt_issuance = sum(outstandingbalance, na.rm = TRUE))

LGFV_province <- FinancialVehicleDebt %>%
  filter(!is.na(abs_province) & !is.na(issue_year) == TRUE) %>%
  group_by(abs_province, issue_year) %>%
  summarise(FVdebt_issuance = sum(outstandingbalance, na.rm = TRUE))

GovernmentDebt_province <- GovernmentDebt %>%
  filter(!is.na(abs_province) & !is.na(issue_year) == TRUE) %>%
  group_by(abs_province, issue_year) %>%
  summarise(GOVdebt_issuance = sum(outstandingbalance, na.rm = TRUE))

LocalDebt_full <- full_join(LGFV_province, GovernmentDebt_province, by = c("abs_province", "issue_year"))

LocalDebt_full %<>%
  ungroup() %>%
  mutate(abs_province = recode(abs_province, 北京 = "北京市", 重庆 = "重庆市", 上海 = "上海市", 
                               天津 = "天津市")) %>%
  mutate(en_province = recode(abs_province, 安徽省 = "Anhui", 北京市 = "Beijing",
                              重庆市 = "Chongqing", 福建省 = "Fujian", 甘肃省 = "Gansu", 
                              广东省 = "Guangdong", 广西壮族自治区 = "Guangxi", 贵州省 = "Guizhou",
                              海南省 = "Hainan", 河北省 = "Hebei", 黑龙江省 = "Heilongjiang",
                              河南省 = "Henan", 湖北省 = "Hubei", 湖南省 = "Hunan", 
                              内蒙古自治区 = "Inner Mongolia", 江苏省 = "Jiangsu", 江西省 = "Jiangxi",
                              吉林省 = "Jilin", 辽宁省 = "Liaoning", 青海省 = "Qinghai",
                              陕西省 = "Shannxi", 山东省 = "Shandong", 上海市 = "Shanghai",
                              山西省 = "Shanxi", 四川省 = "Sichuan", 天津市 = "Tianjin",
                              西藏自治区 = "Tibet", 新疆维吾尔自治区 = "Xinjiang", 云南省 = "Yunnan",
                              宁夏回族自治区 = "Ningxia", 浙江省 = "Zhejiang")) %>%
  mutate(region = case_when(
    abs_province %in% c("黑龙江省","吉林省","辽宁省") ~ "northeast",
    abs_province %in% c("山西省", "河南省", "湖北省", "湖南省", "江西省", "安徽省") ~ "central",
    abs_province %in% c("北京市", "天津市", "河北省", "山东省", "江苏省", "上海市", 
                      "浙江省", "福建省", "广东省", "海南省") ~ "east",
    abs_province %in% c("重庆市", "四川省", "广西壮族自治区", "贵州省", "云南省", "陕西省", "甘肃省", 
                      "内蒙古自治区", "宁夏回族自治区", "新疆维吾尔自治区", 
                      "青海省", "西藏自治区") ~ "west"))

```

```{r public finance data wrangle}

GDP_by_province_1999_2017 <- read_csv("data/public finance/GDP by province 1999-2017.csv", 
    col_types = cols( `2018` = col_skip()), skip = 3)

GDP <- GDP_by_province_1999_2017 %>%
  select(Region, `2017`, `2016`, `2015`, `2014`, `2013`, `2012`) %>%
  gather(`2017`, `2016`, `2015`, `2014`, `2013`, `2012`, key = "year", value = "GDP") %>%
  drop_na(GDP) %>%
  mutate(year = as.numeric(year))

public_finance_all <- read_excel("data/public finance/Anhui 2014-2016.xlsx", 
                                 col_types = c("text", "text", "numeric", "numeric", "numeric")) %>%
  bind_rows((read_excel("data/public finance/Beijing 2014 - 2016.xlsx", 
                                 col_types = c("text", "text", "numeric", "numeric", "numeric")))) %>%
  bind_rows((read_excel("data/public finance/Chongqing 2014 - 2016.xlsx", 
                                 col_types = c("text", "text", "numeric", "numeric", "numeric")))) %>%
  bind_rows((read_excel("data/public finance/Fujian 2014 - 2016.xlsx", 
                                 col_types = c("text", "text", "numeric", "numeric", "numeric")))) %>%
  bind_rows((read_excel("data/public finance/Gansu 2014 - 2016.xlsx", 
                                 col_types = c("text", "text", "numeric", "numeric", "numeric")))) %>%
  bind_rows((read_excel("data/public finance/Guangdong 2014 - 2016.xlsx", 
                                 col_types = c("text", "text", "numeric", "numeric", "numeric")))) %>%
  bind_rows((read_excel("data/public finance/Guangxi 2014 - 2016.xlsx", 
                                 col_types = c("text", "text", "numeric", "numeric", "numeric")))) %>%
  bind_rows((read_excel("data/public finance/Guizhou 2014 - 2016.xlsx", 
                                 col_types = c("text", "text", "numeric", "numeric", "numeric")))) %>%
  bind_rows((read_excel("data/public finance/Hainan 2014 - 2016.xlsx", 
                                 col_types = c("text", "text", "numeric", "numeric", "numeric")))) %>%
  bind_rows((read_excel("data/public finance/Hebei 2014 - 2016.xlsx", 
                                 col_types = c("text", "text", "numeric", "numeric", "numeric")))) %>%
  bind_rows((read_excel("data/public finance/Heilongjiang 2014 - 2016.xlsx", 
                                 col_types = c("text", "text", "numeric", "numeric", "numeric")))) %>%
  bind_rows((read_excel("data/public finance/Henan 2014 - 2016.xlsx", 
                                 col_types = c("text", "text", "numeric", "numeric", "numeric")))) %>%
  bind_rows((read_excel("data/public finance/Hubei 2014 - 2016.xlsx", 
                                 col_types = c("text", "text", "numeric", "numeric", "numeric")))) %>%
  bind_rows((read_excel("data/public finance/Hunan 2014 - 2016.xlsx", 
                                 col_types = c("text", "text", "numeric", "numeric", "numeric")))) %>%
  bind_rows((read_excel("data/public finance/InnerMongolia 2014 - 2016.xlsx", 
                                 col_types = c("text", "text", "numeric", "numeric", "numeric")))) %>%
  bind_rows((read_excel("data/public finance/Jiangsu 2014 - 2016.xlsx", 
                                 col_types = c("text", "text", "numeric", "numeric", "numeric")))) %>%
  bind_rows((read_excel("data/public finance/Jiangxi 2014 - 2016.xlsx", 
                                 col_types = c("text", "text", "numeric", "numeric", "numeric")))) %>%
  bind_rows((read_excel("data/public finance/Jilin 2014 - 2016.xlsx", 
                                 col_types = c("text", "text", "numeric", "numeric", "numeric")))) %>%
  bind_rows((read_excel("data/public finance/Liaoning 2014 - 2016.xlsx", 
                                 col_types = c("text", "text", "numeric", "numeric", "numeric")))) %>%
  bind_rows((read_excel("data/public finance/Ningxia 2014 - 2016.xlsx", 
                                 col_types = c("text", "text", "numeric", "numeric", "numeric")))) %>%
  bind_rows((read_excel("data/public finance/Qinghai 2014 - 2016.xlsx", 
                                 col_types = c("text", "text", "numeric", "numeric", "numeric")))) %>%
  bind_rows((read_excel("data/public finance/Shandong 2014 - 2016.xlsx", 
                                 col_types = c("text", "text", "numeric", "numeric", "numeric")))) %>%
  bind_rows((read_excel("data/public finance/Shanghai 2014 - 2016.xlsx", 
                                 col_types = c("text", "text", "numeric", "numeric", "numeric")))) %>%
  bind_rows((read_excel("data/public finance/Shannxi 2014 - 2016.xlsx", 
                                 col_types = c("text", "text", "numeric", "numeric", "numeric")))) %>%
  bind_rows((read_excel("data/public finance/Shanxi 2014 - 2016.xlsx", 
                                 col_types = c("text", "text", "numeric", "numeric", "numeric")))) %>%
  bind_rows((read_excel("data/public finance/Sichuan 2014 - 2016.xlsx", 
                                 col_types = c("text", "text", "numeric", "numeric", "numeric")))) %>%
  bind_rows((read_excel("data/public finance/Tianjing 2014 - 2016.xlsx", 
                                 col_types = c("text", "text", "numeric", "numeric", "numeric")))) %>%
  bind_rows((read_excel("data/public finance/Tibet 2014 - 2016.xlsx", 
                                 col_types = c("text", "text", "numeric", "numeric", "numeric")))) %>%
  bind_rows((read_excel("data/public finance/Xinjiang 2014 - 2016.xlsx", 
                                 col_types = c("text", "text", "numeric", "numeric", "numeric")))) %>%
  bind_rows((read_excel("data/public finance/Yunnan 2014 - 2016.xlsx", 
                                 col_types = c("text", "text", "numeric", "numeric", "numeric")))) %>%
  bind_rows((read_excel("data/public finance/Zhejiang 2014 - 2016.xlsx", 
                                 col_types = c("text", "text", "numeric", "numeric", "numeric"))))

public_finance_all %<>%
  gather(`2014`, `2015`, `2016`, key = "year", value = "num") %>%
  spread(variable, num) %>%
  mutate(en_province = recode(province, 安徽省 = "Anhui", 北京市 = "Beijing",
                              重庆市 = "Chongqing", 福建省 = "Fujian", 甘肃省 = "Gansu", 
                              广东省 = "Guangdong", 广西壮族自治区 = "Guangxi", 贵州省 = "Guizhou",
                              海南省 = "Hainan", 河北省 = "Hebei", 黑龙江省 = "Heilongjiang",
                              河南省 = "Henan", 湖北省 = "Hubei", 湖南省 = "Hunan", 
                              内蒙古自治区 = "Inner Mongolia", 江苏省 = "Jiangsu", 江西省 = "Jiangxi",
                              吉林省 = "Jilin", 辽宁省 = "Liaoning", 青海省 = "Qinghai",
                              陕西省 = "Shannxi", 山东省 = "Shandong", 上海市 = "Shanghai",
                              山西省 = "Shanxi", 四川省 = "Sichuan", 天津市 = "Tianjin",
                              西藏自治区 = "Tibet", 新疆维吾尔自治区 = "Xinjiang", 云南省 = "Yunnan",
                              宁夏回族自治区 = "Ningxia",浙江省 = "Zhejiang"))
source("2017PublicFinanceDataImport.R")
public_finance <- public_finance_2014_17_all_tidy %>%
  select(province, en_province, year, revenue_all, revenue_alltax, revenue_allnontax, 
         revenue_vat, revenue_business_tax, revenue_lease, revenue_landuse_tax, 
         revenue_landappr_tax, revenue_central_transfer, revenue_debt_onbook,
         spending_all, spending_debtservice, total_balance) %>%
  mutate(year_lag = year + 1)

population_full <- read_csv("data/Population by province.csv", 
                            col_types = cols(`2018` = col_skip()), skip = 3)

population <- population_full %>%
  select(Region, `2017`, `2016`, `2015`, `2014`, `2013`, `2012`) %>%
  gather(`2017`, `2016`, `2015`, `2014`, `2013`, `2012`, key = "year", value = "population") %>%
  drop_na(population) %>%
  mutate(year = as.numeric(year))


Debt_finance_GDP_population_full <- LocalDebt_full %>%
  left_join(public_finance, 
            by = c("abs_province" = "province", "issue_year" = "year", "en_province" = "en_province")) %>%
  left_join(GDP, by = c("en_province" = "Region", "issue_year" = "year")) %>%
  left_join(population, by = c("en_province" = "Region", "issue_year" = "year")) %>%
  rename(province = abs_province, year = issue_year)
```

```{r calculating new variable}

debt_analysis <- Debt_finance_GDP_population_full %>%
  mutate(GOVdebt_to_tax = GOVdebt_issuance/revenue_alltax, GOVdebt_to_GDP = GOVdebt_issuance/GDP) %>%
  select(province, en_province, region, year, GOVdebt_issuance, GOVdebt_to_tax, GOVdebt_to_GDP,
         FVdebt_issuance, GDP, population, everything())

## For year lag dataset population and debt are the same year while other variables are last years
debt_analysis_yearlag <- debt_analysis %>%
  left_join(public_finance, by = c("year" = "year_lag", "en_province"))
```

# Top 10 Debt (to Tax) province from 2014 to 2017

```{r column chart}
debt_analysis %>%
  filter(year >= 2015 & year <= 2017) %>% ## year is numeric
  mutate(year = as.factor(year)) %>%
  group_by(year, region) %>%
  summarize(debt = sum(GOVdebt_issuance, na.rm = TRUE)) %>% ## Remove NA
  ggplot(mapping = aes(x = year, y = debt, fill = region)) + 
  geom_col()

debt_analysis %>%
  filter(year == 2015) %>%
  top_n(n = 10, wt = GOVdebt_issuance) %>%
  ggplot(aes(x = reorder(factor(en_province), GOVdebt_issuance), y = GOVdebt_issuance, fill = region)) +
  geom_col() + 
  coord_flip() +
  labs(title = "Top 10 Government Debt Issuance 2015", 
       x = "Provinces", y = "Debt Issuance (100 million yuan)")
  
debt_analysis %>%
  filter(year == 2016) %>%
  top_n(n = 10, wt = GOVdebt_issuance) %>%
  ggplot(aes(x = reorder(factor(en_province), GOVdebt_issuance), y = GOVdebt_issuance, fill = region)) +
  geom_col() + 
  coord_flip() +
  labs(title = "Top 10 Government Debt Issuance 2016", 
       x = "Provinces", y = "Debt Issuance (100 million yuan)")

debt_analysis %>%
  filter(year == 2017) %>%
  top_n(n = 10, wt = GOVdebt_issuance) %>%
  ggplot(aes(x = reorder(factor(en_province), GOVdebt_issuance), y = GOVdebt_issuance, fill = region)) +
  geom_col() + 
  coord_flip() +
  labs(title = "Top 10 Government Debt Issuance 2017", 
       x = "Provinces", y = "Debt Issuance (100 million yuan)")

debt_analysis %>%
  filter(year == 2018) %>%
  top_n(n = 10, wt = FVdebt_issuance) %>%
  ggplot(aes(x = reorder(factor(en_province), FVdebt_issuance), y = FVdebt_issuance, fill = region)) +
  geom_col() + 
  coord_flip() +
  labs(title = "Top 10 LGFV Debt Issuance 2018", 
       x = "Provinces", y = "Debt Issuance (100 million yuan)")

debt_analysis %>%
  filter(year == 2015) %>%
  top_n(n = 10, wt = GOVdebt_to_tax) %>%
  ggplot(aes(x = reorder(factor(en_province), GOVdebt_to_tax), y = GOVdebt_to_tax, fill = region)) +
  geom_col() + 
  coord_flip() +
  labs(title = "Top 10 Government Debt Issuance to Tax ratio 2015", 
       x = "Provinces", y = "Debt Issuance to Tax Ratio")

debt_analysis %>%
  filter(year == 2016) %>%
  top_n(n = 10, wt = GOVdebt_to_tax) %>%
  ggplot(aes(x = reorder(factor(en_province), GOVdebt_to_tax), y = GOVdebt_to_tax, fill = region)) +
  geom_col() +
  coord_flip() +
  labs(title = "Top 10 Government Debt to Tax Issuance ratio 2016", 
       x = "Provinces", y = "Debt Issuance to Tax Ratio")

debt_analysis %>%
  filter(year == 2017) %>%
  top_n(n = 10, wt = GOVdebt_to_tax) %>%
  ggplot(aes(x = reorder(factor(en_province), GOVdebt_to_tax), y = GOVdebt_to_tax, fill = region)) +
  geom_col() +
  coord_flip() +
  labs(title = "Top 10 Government Debt to Tax Issuance ratio 2017", 
       x = "Provinces", y = "Debt to Tax Issuance Ratio")

```

# Mapping the Debt

```{r mapping}
china_admin <- st_read("data/chn_admbnda_adm1_ocha/chn_admbnda_adm1_ocha.shp") %>%
  filter(ADM1_ZH != "台湾省") 

china_admin %>%
  left_join(filter(debt_analysis, year == 2018), by = c("ADM1_ZH" = "province")) %>%
  ggplot() +
  geom_sf(aes(fill = FVdebt_issuance)) +
  scale_fill_viridis(option = "inferno", labels = scales::dollar, na.value = "white") +
  labs(title = "2018 financial vehicle debt", fill = "RMB 100 million")

china_admin %>%
  left_join(filter(debt_analysis_yearlag, year_lag == 2018),  by = c("ADM1_ZH" = "province.x")) %>%
  mutate(FVdebt_to_tax = FVdebt_issuance/revenue_alltax.x) %>%
  ggplot() +
  geom_sf(aes(fill = FVdebt_to_tax)) +
  scale_fill_viridis(option = "inferno", labels = scales::percent, na.value = "white") +
  labs(title = "2018 financial vehicle debt", fill = "Debt to Tax Ratio")

china_admin %>%
  left_join(filter(debt_analysis, year == 2017), by = c("ADM1_ZH" = "province")) %>%
  ggplot() +
  geom_sf(aes(fill = GOVdebt_to_tax)) +
  scale_fill_viridis(option = "inferno", labels = scales::percent, na.value = "white") +
  labs(title = "2017 Government Debt", fill = "Debt to Tax Income Ratio")

china_admin %>%
  left_join(filter(debt_analysis, year == 2016), by = c("ADM1_ZH" = "province")) %>%
  ggplot() +
  geom_sf(aes(fill = GOVdebt_to_tax)) +
  scale_fill_viridis(option = "inferno", labels = scales::percent, na.value = "white") +
  labs(title = "2016 Government Debt", fill = "Debt to Tax Income Ratio")

china_admin %>%
  left_join(filter(debt_analysis, year == 2015), by = c("ADM1_ZH" = "province")) %>%
  ggplot() +
  geom_sf(aes(fill = GOVdebt_to_tax)) +
  scale_fill_viridis(option = "inferno", labels = scales::percent, na.value = "white") +
  labs(title = "2015 Government Debt", fill = "Debt to Tax Income Ratio")

```

# Modeling the Debt

```{r simple modelling}

debt_regression <- debt_analysis_yearlag %>%
  mutate(population_log = log10(population), GDP_log = log10(GDP), 
         deficit.x = spending_all.x - revenue_all.x,
         deficit.y = spending_all.y - revenue_all.y,
         deficit.x_log = log10(deficit.x),
         deficit.y_log = log10(deficit.y),
         revenue_alltax.x_log = log10(revenue_alltax.x), 
         revenue_alltax.y_log = log10(revenue_alltax.y),
         revenue_central_transfer.x_log = log10(revenue_central_transfer.x),
         revenue_central_transfer.y_log = log10(revenue_central_transfer.y),
         revenue_central_transfer.x_ratio = revenue_central_transfer.x/revenue_alltax.x,
         revenue_central_transfer.y_ratio = revenue_central_transfer.y/revenue_alltax.y)

## pooled data 

z.base <- zelig(GOVdebt_to_tax ~ population_log + GDP_log + revenue_alltax.x_log,
                model = "normal", data = debt_regression)

z.base_yearlag <- zelig(GOVdebt_to_tax ~ population_log + GDP_log + revenue_alltax.y_log,
                        model = "normal", data = debt_regression)

z.region <- zelig(GOVdebt_to_tax ~ population_log + revenue_alltax.x_log + region,
                  model = "normal", data = debt_regression)

z.transfer <- zelig(GOVdebt_to_tax ~ population_log + GDP_log + revenue_central_transfer.x_log, 
                    model = "normal", data = debt_regression)

z.transfer_yearlag <- zelig(GOVdebt_to_tax ~ population_log + GDP_log + revenue_central_transfer.y_log, 
                            model = "normal", data = debt_regression)

z.transfer_control <- zelig(GOVdebt_to_tax ~ population_log + GDP_log + revenue_alltax.x_log + 
                              revenue_central_transfer.x_log, model = "normal", 
                            data = debt_regression)

z.transfer_control_yearlag <- zelig(GOVdebt_to_tax ~ population_log + GDP_log + 
                                      revenue_alltax.y_log + revenue_central_transfer.y_log, 
                                    model = "normal", 
                                    data = debt_regression)

z.transferratio <- zelig(GOVdebt_to_tax ~ population_log + GDP_log + 
                           revenue_alltax.x_log + revenue_central_transfer.x_ratio, 
                         model = "normal", data = debt_regression)

z.transferratio_yearlag <- zelig(GOVdebt_to_tax ~ population_log + GDP_log + 
                                   revenue_alltax.y_log + revenue_central_transfer.y_ratio, 
                                 model = "normal", data = debt_regression)

z.deficit <- zelig(GOVdebt_to_tax ~ population_log + GDP_log + deficit.x_log, 
                   model = "normal", data = debt_regression)

z.deficit_yearlag <- zelig(GOVdebt_to_tax ~ population_log + GDP_log + deficit.y_log, 
                           model = "normal", data = debt_regression)

z.deficit_control <- zelig(GOVdebt_to_tax ~ population_log + GDP_log + revenue_alltax.x_log + 
                             deficit.x_log, model = "normal", 
                           data = debt_regression)

z.deficit_control_yearlag <- zelig(GOVdebt_to_tax ~ population_log + GDP_log + revenue_alltax.y_log + 
                                     deficit.y_log, model = "normal", 
                                   data = debt_regression)

z.all <- zelig(GOVdebt_to_tax ~ population_log + GDP_log + revenue_alltax.x_log + 
                 deficit.x_log + revenue_central_transfer.x_log,
               model = "normal", data = debt_regression)

z.all_yearlag <- zelig(GOVdebt_to_tax ~ population_log + GDP_log + revenue_alltax.y_log + 
                         deficit.y_log + revenue_central_transfer.y_log,
                       model = "normal", data = debt_regression)

summary(z.base)
summary(z.base_yearlag)
summary(z.region)
summary(z.transfer)
summary(z.transfer_yearlag)
summary(z.transfer_control)
summary(z.transfer_control_yearlag)
summary(z.transferratio)
summary(z.transferratio_yearlag)
summary(z.deficit)
summary(z.deficit_yearlag)
summary(z.deficit_control)
summary(z.deficit_control_yearlag)
summary(z.all)
summary(z.all_yearlag)

```
